---

- name: "Install httpd"
  yum:
    name: httpd
    state: present
  when: ansible_os_family == 'RedHat'
  tags: 
    - httpd

- name: Start httpd.
  service:
    name: httpd
    state: started
    enabled: true
  tags: 
    - httpd

- name: create httpd directories if it does not exist
  file:
    path: "{{ item.www }}"
    state: directory
    mode: 0755
    owner: "{{ httpd_user }}"
    group: "{{ httpd_group }}"
  with_items:
    "{{ httpd_virtualhost }}"
  tags: 
    - httpd
  
- name: Copy virtualhosts conf.
  template:
    src: "virtualhost.conf.j2"
    dest: "{{ httpd_home }}/conf.d/{{ item.domain }}.conf"
    owner: apache
    group: apache
    mode: 0644
  with_items:
    "{{ httpd_virtualhost }}" 
  notify: restart httpd
  tags: 
    - httpd

- name: enable servername 80
  lineinfile:
    dest: "{{ httpd_home }}/conf/httpd.conf"
    regexp: "^ServerName localhost:80"
    line: "ServerName localhost:80"
    state: present
  notify: restart httpd
  tags: 
    - httpd

- name: Add apache mod mpm worker configuration.
  template:
    src: "00-mpm.conf.j2"
    dest: "{{ httpd_home }}/conf.modules.d/00-mpm.conf"
    owner: root
    group: root
    mode: 0644
  with_items: "{{httpd_settings}}"
  notify: restart httpd
  tags: 
    - httpd
  
- name: Add apache vhosts configuration.
  template:
    src: "{{ item }}.conf.j2"
    dest: "{{ httpd_home }}/conf.d/{{ item }}.conf"
    owner: root
    group: root
    mode: 0644
  with_items: "{{httpd_settings}}"
  notify: restart httpd
  tags: 
    - httpd
